---
- name: Apply the sysctl value to enable TCP Fast Open
  sysctl:
    name: net.ipv4.tcp_fastopen
    value: 3
    state: present

    #- name: Install the Shadowsocks dependencies
    #  apt:
    #    name: "{{ item }}"
    #    install_recommends: no
    #  with_items: "{{ shadowsocks_dependencies }}"
    #
    #- name: Retrieve Shadowsocks-libev souce code
    #  git:
    #    repo: https://github.com/shadowsocks/shadowsocks-libev.git
    #    dest: "{{ shadowsocks_compilation_directory }}"
    #    version: "{{ shadowsocks_version }}"
    #
    #- name: Compile and install Shadowsocks-libev
    #  shell: ./autogen.sh && ./configure && make -j {{ ansible_processor_cores }} && make install
    #  args:
    #    chdir: "{{ shadowsocks_compilation_directory }}"

- name: Install shadowsocks-libev
  apt:
    name: shadowsocks-libev

- name: Generate a random Shadowsocks password
  shell: openssl rand -base64 48 > {{ shadowsocks_password_file }}
  args:
    creates: "{{ shadowsocks_password_file }}"

- name: Register Shadowsocks password
  command: cat {{ shadowsocks_password_file }}
  register: shadowsocks_password

- name: Generate Shadowsocks config file
  template:
    src: config.json.j2
    dest: "{{ shadowsocks_location }}/config.json"
    mode: 0640
  notify: Restart shadowsocks-libev

- name: Create the Shadowsocks Gateway directory
  file:
    path: "{{ shadowsocks_gateway_location }}"
    owner: www-data
    group: www-data
    mode: 0750
    state: directory

- name: Generate the Markdown Shadowsocks instructions
  template:
    src: instructions.md.j2
    dest: "{{ shadowsocks_markdown_instructions }}"

- name: Convert the Markdown Shadowsocks instructions into HTML and surround them with the header and footer template
  shell: markdown {{ shadowsocks_markdown_instructions }} | cat {{ streisand_header_template }} - {{ streisand_footer_template }} > {{ shadowsocks_html_instructions }}

- name: Generate the Shadowsocks QR code
  # The ss:// URI format is documented here:
  #   http://shadowsocks.org/en/config/quick-guide.html
  shell: echo -n '{{ shadowsocks_encryption_method }}-auth:{{ shadowsocks_password.stdout }}@{{ streisand_ipv4_address }}:{{ shadowsocks_server_port }}' | base64 --wrap=0 | sed 's/^/ss:\/\//' | qrencode -s 8 -o {{ shadowsocks_qr_code }}

- name: Set permissions on the Shadowsocks password file
  file:
    path: "{{ shadowsocks_password_file }}"
    owner: root
    group: root
    mode: 0600
